#ifndef __MESSAGE_H__
#define __MESSAGE_H__

class Message
{
	enum EMESSAGE_TYPE
	{
		EMESSAGE_TYPE_ERROR_RESOURCE_NOT_FOUND,
		EMESSAGE_TYPE_ERROR_RESOURCE_NOT_SEEKABLE,
		EMESSAGE_TYPE_INFO_ADDED_FEEDER,
		EMESSAGE_TYPE_INFO_FLUSH,
	};

	const EMESSAGE_TYPE m_eType;

	Message(EMESSAGE_TYPE a_eType){m_eType = a_eType}
	EMESSAGE_TYPE GetType(){	return m_eType; }
}

#endif //__MESSAGE_H__
